name: Deploy to AWS EBS and Docker

on:
  workflow_call:
    secrets:
      AWS_EB_APP_NAME:
        required: true

env:
  APP_VERSION_LABEL: ${{ secrets.AWS_EB_APP_NAME }}-${GITHUB_RUN_ID}-${GITHUB_SHA}-${GITHUB_RUN_ATTEMPT}

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout Actions repository
        uses: actions/checkout@v3
        with:
          repository: Nasdan/actions
          ref: main
          path: tmp
      - name: Copy EBS deploy folders
        run: |
          cp -R /tmp/.ebextensions /.ebextensions
          cp -R /tmp/.platform /.platform
          rm -rf tmp
      - name: Checking
        run: |
          ls -a
          ls -a .github/workflows
          ls -a .ebextensions
          echo ${{env.APP_VERSION_LABEL}}
